#if !canImport(ObjectiveC)
import XCTest

extension PollResultsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PollResultsTests = [
        ("testMultipleAnswers", testMultipleAnswers),
        ("testMultipleLosers", testMultipleLosers),
        ("testMultipleWinners", testMultipleWinners),
        ("testSingleAnswer", testSingleAnswer),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PollResultsTests.__allTests__PollResultsTests),
    ]
}
#endif
